name: Deploy Jekyll site to Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          ruby -v
          sudo gem install bundler

      - name: Install dependencies
        run: |
          bundle config set path 'vendor/bundle'
          bundle install

      - name: Build site
        run: bundle exec jekyll build

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
